### ISSUE TITLE
Unity 6 support

### ISSUE THREAD

**Issue by Bersaelor** [Macoron/whisper.unity#106]
Hey @Macoron , 

any plans on supporting Unity 6?

I checked out the repo, opened it in Unity 6 on mac silicone and the samples don't work.
It compiles fine but speech recognition always just says `[Music]` or `[Gunfire]` or `[Clearing]` when I say `Test Test Test`.

**Comment by Bersaelor** [comment]
Turns out the issue was that Unity6 has a problem with bluetooth headsets (Apple AirPods in my case).
The Bluetooth headset works fine with a whisper sample app in the browser using typescript, so I didn't think it was the connection, but when recording via unity the audioclip is very low quality. And then the transcription doesn't work.

**Comment by joshuawilde** [comment]
@Bersaelor did you ever find a fix for this? It happens to me too on Unity 2022.
