### ISSUE TITLE
Not compatible with Unity 2020 (works with 2021) 

### ISSUE THREAD

**Issue by chriswalz** [Macoron/whisper.unity#13]
![image](https://user-images.githubusercontent.com/6971318/232972322-4b30f166-d04c-48a3-9742-c5c406692f86.png)

`Library\PackageCache\com.whisper.unity@9877bf753c\Runtime\Utils\MainThreadDispatcher.cs(13,63): error CS8124: Tuple must contain at least two elements.`

**Comment by SharafeevRavil** [comment]
The first error is related to the use of the `new()` construct:
`private readonly ConcurrentQueue<Task> _actions = new();`
[Omitting the type in a new expression feature](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#fit-and-finish-features) was added in C# 9.

I can suggest some workarounds:
1. Try to change the .NET version in the project settings
2. Fix incompatibility errors manually (preferably if point 1 didn't help)
3. Build this library in .NET Standard 2.0 and use the resulting .dll file

**Comment by Macoron** [comment]
I made new PR to fix that. @chriswalz reopen this if you still have problems with latest version.

**Comment by chriswalz** [comment]
Thank you for this fix!
