### ISSUE TITLE
Microphone streaming

### ISSUE THREAD

**Issue by Macoron** [Macoron/whisper.unity#14]
Whisper.cpp has [this demo](https://github.com/ggerganov/whisper.cpp/tree/master/examples/stream) of real-time transcription from microphone stream. There are two modes: simple and VAD. It would be really good to implement something similar in Unity.

**Comment by tsepton** [comment]
Has there been any progress on this issue?

**Comment by Macoron** [comment]
Yikes, it was added by #40. I forgot to close this issue.

There is still some work to make it work more stable (see #45), but first version is already merged into latest master.
