### ISSUE TITLE
Linux (Ubuntu) support?

### ISSUE THREAD

**Issue by tkoterwas** [Macoron/whisper.unity#19]
This worked flawlessly for me on my Mac but I need to run it on my Ubuntu system because other aspects of the project aren't compatible with Mac (this is for a physical art installation rather than a broad cross-platform release). I've tried compiling whisper.cpp on my Ubuntu system manually by following the example set in build_cpp.sh for other platforms (obv without their specific cmake flags), and then copied the resulting libwhisper.so from whisper.ccp/build into the Assets folder but it crashes on the call to whisper_full_with_state with a segmentation fault: `Caught fatal signal - signo:11 code:1 errno:0 addr:0x04000`

If i build whisper.cpp as an executable using just Make as per the whisper.cpp ReadMe it works fine as a standalone executable. 

Any advice on how to make this work? I recognise this might be an issue with whisper.cpp but I thought I'd start here to see if anyone else has had any luck with trying to use this on Ubuntu. I've spent several days googling and trying various things but am far from a cmake expert, so perhaps I need to set some ubuntu-specific options? 

I've tried multiple recent Unity releases, starting with 2021.3.3f1 and currently running 2021.23.f1 and I've tried setting the player's scripting backend to both mono and IL2CPP with no luck.

Any help or advice would be greatly appreciated.

System Specs:
OS: Ubuntu 22.04.2 LTS
Memory: 16GB
CPU: 12th gen Intel i7-12700H
GPU: NVIDIA GeForce RTX 3060 Mobile
Hardware: MSI Crosshair 15

**Comment by Macoron** [comment]
Unfortunately, I don't have Ubuntu x64 machine right now, so I can't fully debug or support it myself. 

However, `whisper_full_with_state` was introduced in [whisper.cpp 1.3.0](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.3.0). This library uses [whisper.cpp 1.2.1](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.2.1). Newer version probably not compatible with Unity bindings, so try to downgrade it to 1.2.1 and recompile it.

If it doesn't help, please provide your cmake command line command and last messages of [Unity Editor log](https://docs.unity3d.com/Manual/LogFiles.html). Maybe it has some clues what has gone wrong.

**Comment by tkoterwas** [comment]
@Macoron thanks so much!! it's working fine with whisper.cpp 1.2.1 I added the following to build_cpp.sh and ran it (so literally just a vanilla cmake call): 
```
build_ubuntu() {
  clean_build
  echo "Starting building for Ubuntu..."

  cmake ../
  make

  echo "Build for Ubuntu complete!"

  artifact_path="libwhisper.so"
  target_path="$unity_project/Packages/com.whisper.unity/Plugins/Ubuntu/libwhisper.so"
  cp "$artifact_path" "$target_path"

  echo "Build files copied to $target_path"

}
```
