### ISSUE TITLE
Unity crash! Whisper 

### ISSUE THREAD

**Issue by ehabtawfikelbwab** [Macoron/whisper.unity#23]
Hi Macoron,

When I use whisperManager.GetTextAsync(savedClip);
unity crash's 
after debug "Inference Whisper on input data..."

when i did change this :
var code = WhisperNative.whisper_full(_whisperCtx, param, samplesPtr, samples.Length);

to :
var code = 0;
unity works good but the final text is null or empty

Also can i add list of word which make Whisper focus on it (Like keyPhrases in Vosk)

Thank you very much

my email:
ehabelbwab75@gmail.com

Ehab Elbwab

**Comment by Macoron** [comment]
Hey @ehabtawfikelbwab. Could you provide more info about crash? I would need:

1. What version of whisper.unity you are using? Are you using examples provided with this repo?
2. Your platform (Windows, Mac, etc) and its version?
3. What is your hardware specs (CPU and RAM)?
4. Do you use custom audio clip or provided in example `jfk.wav`?
5. Please send last messages in [Unity Editor logs file](https://docs.unity3d.com/Manual/LogFiles.html). In file there should be some additional info about C++ error that crashed Unity.

Also, could you please check does original whisper.cpp works on your machine. [Here is a link](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.2.1), if you are using Windows there is already builded .exe files that you can run and test.

**Comment by ehabtawfikelbwab** [comment]
1- Unity 2021.3.9f1
2- Windows
3- intel i5 - 3470 / ram : 12GB
4-after record from AudioSource i'm saving the file "STT.flac" then i call it again by AudioClip.Create();

`var clipData = WavUtility.Save(Application.persistentDataPath + "/" + "STT", voiceProcessor._audioSource.clip);

            if (!clipData)
            {
                Debug.LogError("Clip not found.Wav");

                Reset_Wait_WakeWord();
                return;
            }

            doneTalking = false;
            voiceProcessor.StopRecording();

            // Load the WAV file into a byte array
            byte[] wavBytes = System.IO.File.ReadAllBytes(Application.persistentDataPath + "/" + "STT.flac");

            // Convert the byte array to a float array
            float[] audioData = new float[wavBytes.Length / 2];
            for (int i = 0; i < audioData.Length; i++)
            {
                short s = (short)(wavBytes[i * 2] | wavBytes[i * 2 + 1] << 8);
                audioData[i] = s / 32768.0f;
            }

            // Create a new AudioClip
            AudioClip clip = AudioClip.Create("ehab", audioData.Length, 1, 16000, false);
            clip.SetData(audioData, 0);

            WhisperResult result = await whisperManager.GetTextAsync(clip);`
            
[Editor.log](https://github.com/Macoron/whisper.unity/files/11472608/Editor.log)

**Comment by Macoron** [comment]
Does this crashes also in [this](https://github.com/Macoron/whisper.unity/tree/master/Assets/Samples/1%20-%20Audio%20Clip) and [this](https://github.com/Macoron/whisper.unity/tree/master/Assets/Samples/2%20-%20Microphone) samples?

**Comment by ehabtawfikelbwab** [comment]
You can take my pc for as long as you want by using anydesk or teamviewer!

and one more question 
Can I add list of word which make Whisper focus on it (Like keyPhrases in Vosk)?

**Comment by Macoron** [comment]
> You can take my pc for as long as you want by using anydesk or teamviewer!

Sorry, but I don't have time for this. You need to test if original [whisper.cpp](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.2.1) project works on your machine. If my guess that your old CPU doesn't support AVX2 is right, the only thing that I can recommend you is rebuild .dll from source for your CPU limitations or find a new hardware. For rebuilding C++ [check this](https://github.com/Macoron/whisper.unity#compiling-c-libraries-from-source).

> Can I add list of word which make Whisper focus on it (Like keyPhrases in Vosk)?

You can prompt whisper, yes. However this feature isn't yet supported for Unity bindings See #8.

**Comment by Macoron** [comment]
I will move this issue to a new one. If you will have more info about your crashes, fill free to reopen it.
