### ISSUE TITLE
modelPath needs a setter

### ISSUE THREAD

**Issue by achimmihca** [Macoron/whisper.unity#36]
First, thank you so much for this great port of Whisper to Unity ❤️ ! It got me up and running in half no-time with increadibly accurate results 🚀 .

However, I am missing a setter for WhisperManager.modelPath.
The field is private but serialized. So, one can set it in the inspector, but not from code.

As a workaround, I am settings it via reflection at the moment
```
    private void SetWhisperModelPath(WhisperManager whisperManager, string modelPath)
    {
        // Set the model field via reflection, because the property is private.
        FieldInfo prop = whisperManager
            .GetType()
            .GetField("modelPath",
                System.Reflection.BindingFlags.NonPublic
                        | System.Reflection.BindingFlags.Instance);
        prop.SetValue(whisperManager, modelPath);
    }
```

The field does not need to be private. It can be changed as long as InitModel has not been called yet.
```
public string ModelPath
{
    get => modelPath;
    set
    {
        if (IsLoaded || IsLoading)
        {
            throw new InvalidOperationException("Cannot change model path after loading the model!");
        }

        modelPath = value;
    }
}
```

**Comment by Macoron** [comment]
Good point! Could you make a PR with new setter code? I will speed merge that.

**Comment by achimmihca** [comment]
Will do.

Using the streamingAssetsPath as base path should also be optional.
```
var path = Path.Combine(Application.streamingAssetsPath, modelPath);
```
