### ISSUE TITLE
How to see if text is completed in case of microphone streaming

### ISSUE THREAD

**Issue by nikhil-convrseai** [Macoron/whisper.unity#42]
I'm building an application where i want to record the voice, convert it to text and then use it for various other purposes, right now i'm not able to determine when the last text data will come. how can achieve this in unity?

**Comment by Macoron** [comment]
You would probably need to change code here a bit:
https://github.com/Macoron/whisper.unity/blob/6fc87279e7468aa0a72ecedeb6056ae711e4d9c1/Packages/com.whisper.unity/Runtime/WhisperStream.cs#L163-L185

Probably changing ending to something like:
```csharp
// finish last part
await UpdateSlidingWindow(true);
OnStreamFinished?.Invoke(currentOutput);
```

**Comment by KUSACON** [comment]
Thank you @Macoron
