### ISSUE TITLE
immediately start stream - onLoaded (?)

### ISSUE THREAD

**Issue by yosun** [Macoron/whisper.unity#59]
Is there a some sort of callback that is similar to onLoaded, to immediately start stream transcription? 

Currently using a Coroutine to wait 3s before starting mic...

**Comment by Macoron** [comment]
There is no event for loading model weights, but `WhisperManager.CreateStream` is async function. It should wait if model is loading and return only when whisper is ready. You can do something like:
```csharp
private async void Start()
{
    var stream = await manager.CreateStream(mic);
    // do what you need with stream
}
```
