### ISSUE TITLE
Performance on Oculus quest 3

### ISSUE THREAD

**Issue by Loloncio** [Macoron/whisper.unity#71]
Thanks for this, amazing work but is there a way to make it faster? I use it in a game for the Oculus Quest 3 and it needs 20-30 seconds to transcribe a 6 words phrase. I am using the tiny model.

**Comment by Macoron** [comment]
I would recommend to check issue #47. Try to play with parameters like threads number or speed-up to see if it improves transcription speed. If any success, please share it in #47. 

I will close this issue as dupl.
