### ISSUE TITLE
Add prompting support

### ISSUE THREAD

**Issue by Macoron** [Macoron/whisper.unity#8]
Whisper supports adding prompt / vocabulary. It should improve transcription quality or guide it to the right direction. Check this [for more info](https://github.com/ggerganov/whisper.cpp/blob/794ff3074a4fad9926f90dc6e3d838fb81bbc183/whisper.h#L362).

**Comment by SharafeevRavil** [comment]
Created [the pull request that solves it](https://github.com/Macoron/whisper.unity/pull/25)

**Comment by Macoron** [comment]
Closed by #25
