### ISSUE TITLE
Unable to load model

### ISSUE THREAD

**Issue by lex6i** [Macoron/whisper.unity#82]
When trying to run any of the samples I get the error "Failed to load Whisper model"
I'm running the project completely unmodified,  I've tried different models as well without luck.
Any ideas on how to fix this?
using 
unity 2022.3.18f1
windows 10 x64

**Comment by lex6i** [comment]
It seems as it works if I use the supplied project, but not if I only import the package into a excisting project, which still is problematic since I cannot import it into my current project

**Comment by Macoron** [comment]
When installed as a package, you also need to download whisper model weights file `.bin`. They need to be placed in StreamingAssets folder, [same as in example project](https://github.com/Macoron/whisper.unity/tree/master/Assets/StreamingAssets/Whisper). For more info [check here](https://github.com/Macoron/whisper.unity?tab=readme-ov-file#downloading-other-model-weights).

Also make sure that `WhisperManager` have correct path to model weights that you have downloaded. 

Let me know if it doesn't work.

**Comment by lex6i** [comment]
Yess I did that already and tried with different models,  I also confirmed that it's finding the file, but just unable to load it as the error changes to file not found when it's absent

**Comment by Macoron** [comment]
> Yess I did that already and tried with different models, I also confirmed that it's finding the file, but just unable to load it as the error changes to file not found when it's absent

That's very strange. Sample project should work same as a package. Tried to reproduce this problem locally, but it seems to work fine.

As a workaround, you can just copy package files (including scripts, plugins, etc) into your project. It should work same as sample project.

**Comment by Macoron** [comment]
Will close for now. Reopen if you know how to reproduce it.
