### ISSUE TITLE
Version number in package.json is not updated

### ISSUE THREAD

**Issue by from2001** [Macoron/whisper.unity#85]
@Macoron 
Thank you for the great project. I love it.

I found that the version number in package.json is not updated and remains 1.0.0
The number needs to be updated before the release process.

I'll make a pull request of it.

**Comment by from2001** [comment]
I registered whisper.unity on OpenUPM which is an open source Unity package registry, however the latest release was not reflected due to the version number string.

Once the version string is updated, next release should be automatically reflected to the registry. 

https://openupm.com/packages/com.whisper.unity/

**Comment by Macoron** [comment]
Thank you for this PR. I will try keep this json updated with new version releases.
