### ISSUE TITLE
Changing the model breaks transcription, no errors

### ISSUE THREAD

**Issue by violetbeamgames** [Macoron/whisper.unity#92]
Hello!

Thank you very much for your work! I have been able to implement the package in my own project quite easily. 

Now, I am trying to use different models as you explain [here](https://github.com/Macoron/whisper.unity#downloading-other-model-weights) , but with no success. I change the model path on the whisperer manager (E.G "Whisper/ggml-medium.en.bin"), but the transcription doesn't show at all. Everything else seem to be working. I also have no errors, so I'm not sure what I'm doing wrong :/

Thank you!

**Comment by Macoron** [comment]
In `WhisperManager` set log level to "Verbose" and send logs here. Maybe it would help to understand what is going on.

**Comment by Macoron** [comment]
Reopen if you have more info about this issue
